### ISSUE TITLE
Compilation on a Mac

### ISSUE THREAD

**Issue by hulpke** [gap-packages/kbmag#27]
I have been able to compile on a Mac only by calling

```
make CFLAGS="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" LDFLAGS="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
```

Is there any way one could add this to the Makefile? Or should it be added to the README?

**Comment by fingolfin** [comment]
There's a left unsaid in this repot.. I assume you are meaning to convey that on certain macOS versions with certain Xcode versions, there are some kind of issues compiling kbmag (which?) and that you could work around them with the above?

So: which macOS versions, which Xcode, what is the error?

Most likely this is something that affects multiple packages, not just kbmag, perhaps even GAP itself.

**Comment by hulpke** [comment]
MacOS Big Sur 11.2.3
kbmag 1.5.9
XCode 12.4 (12D4e)

Error message, after `configure, make`
```
cc -c -fPIC -O2 -g -Wall -Wno-char-subscripts fsa.c
fsa.c:22:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
```

The same probably affects other C bianries that do not have a full autoconf process. (GAP e.g. compiles fine)

**Comment by fingolfin** [comment]
Thanks! And weird. I am not aware of anything in autoconf that would figure out the path to the SDK, so it must be something else.

I'll try to reproduce this on a similar machine at work and see if I can figure it out.

**Comment by fingolfin** [comment]
I just tried this and could not reproduce the problem on an M1 Mac Mini. Please tell me some more details:
- which GAP version?
- output of the following commands:
  - `sw_vers`
  - `cc --version`
  - `xcode-select -p`
  - `which cc`
  - `mdfind -name stdio.h`

**Comment by hulpke** [comment]
Thank you for checking this. I have now tried on another Mac and also cannot reproduce there. So it probably is an error with my xcode setup, and I thus close the issue.

(I had googled the error message and found pages that indicated the extra flag being needed and it had resolved the issue).

Apologies for the trouble.

**Comment by fingolfin** [comment]
No worries at all, thank you very much for the report, it is difficult to know where auch issues come from.

The output of the commands I listed above might give a clue. Perhaps the Xcode command line tools need to be (re)installed?
