### ISSUE TITLE
Add standard tests

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/kbmag#5]

**Comment by cdwensley** [comment]
Due to problems with another example yesterday, I have started copying the manual examples into a test file.  All going well with Examples 1,2,3, but have hit an error with Example 4 on my system which I will report in a separate issue.

**Comment by cdwensley** [comment]
Advice needed on converting the manual examples into a test file. 
There are a number of messages printed out by the C programs, for example 
#System is confluent.
#Halting with 18 equations.
The Test function appears to ignore such things - is that OK?

**Comment by alex-konovalov** [comment]
@cdwensley is everything now done in #10? If so, can we close this issue?

**Comment by cdwensley** [comment]
Yes. The tests will need tweaking and currently produce errors, but these are different issues.
