### ISSUE TITLE
Error, Could not open output of external Knuth-Bendix program.

### ISSUE THREAD

**Issue by cdwensley** [gap-packages/kbmag#8]
This happened while testing Example 4 (p.13 of the manual).  Is it just my system? 
```
gap> KnuthBendix(R);
#I  Calling external Knuth-Bendix program.
  #60 eqns; total len: lhs, rhs = 129, 143; 25 states; 0 secs.
  #68 eqns; total len: lhs, rhs = 151, 182; 28 states; 0 secs.
  #77 eqns; total len: lhs, rhs = 174, 275; 45 states; 0 secs.
  #91 eqns; total len: lhs, rhs = 229, 364; 58 states; 0 secs.
Error, Could not open output of external Knuth-Bendix program. called from
UpdateRWS( rws, _KBTmpFileName, true 
 ); at /Applications/gap/my-dev/pkg/kbmag/gap/rws4.g:1532 called from
KBRWS( rws 
 ) at /Applications/gap/my-dev/pkg/kbmag/gap/kbsmg2.gi:224 called from
<function "unknown">( <arguments> )
 called from read-eval loop at line 77 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by fingolfin** [comment]
This is likely to be the same problem as in #7 and #9 -- i.e. one of the `kbmag` binaries crashing.

**Comment by fingolfin** [comment]
For my convenience, here is the full input, easily copy&pasteable:
```
gap> F:=FreeGroup("h","g","f","e","d","c","b","a");;
gap> h:=F.1;;g:=F.2;;f:=F.3;;e:=F.4;;d:=F.5;;c:=F.6;;b:=F.7;;a:=F.8;;
gap> G:=F/[Comm(b,a)*c^-1, Comm(c,a)*d^-1, Comm(d,a)*e^-1,
> Comm(e,b)*f^-1, Comm(f,a)*g^-1, Comm(g,b)*h^-1,
> Comm(g,a), Comm(c,b), Comm(e,a)];;
gap> R:=KBMAGRewritingSystem(G);                     
gap> SetOrderingOfKBMAGRewritingSystem(R,"recursive");
gap> O:=OptionsRecordOfKBMAGRewritingSystem(R);
gap> O.maxstoredlen:=[10,10];;
gap> SetInfoLevel(InfoRWS,2);
gap> KnuthBendix(R);
```

**Comment by fingolfin** [comment]
Actually, I can reproduce this problem with kbmag 1.5. So it seems to be an old issue.

**Comment by cdwensley** [comment]
After downloading the latest commits my Kan tests all worked! 
But then, after recompiling, there were still errors. 
Here is the current problem example file: 
## dec07.g
LoadPackage("kbmag");
F4 := FreeGroup("a","b");;
rels4 := [ F4.1^3, F4.2^3, (F4.1*F4.2)^3 ];;
G4 := F4/rels4;;
alph4 := "AaBb";;
rws := KBMAGRewritingSystem( G4 );
ok := AutomaticStructure( rws );
Here is the result in GAP: 
gap> Read("dec07.g");
/Applications/gap/my-dev/pkg/kbmag/bin/x86_64-apple-darwin16.7.0-gcc-default64/autgroup: line 133:  2684 Segmentation fault: 11  $GPMAKEFSA $gpmakefsaflags $groupname
#Program to construct word-acceptor and multiplier automata failed. Giving up.
gap> rws;
rec(
           isRWS := true,
          silent := true,
  generatorOrder := [_g1,_g2,_g3,_g4],
        inverses := [_g2,_g1,_g4,_g3],
        ordering := "shortlex",
       equations := [
         [_g1^2,_g2],
         [_g3^2,_g4],
         [_g1*_g3*_g1,_g4*_g2*_g4]
       ]
)

**Comment by fingolfin** [comment]
For me (using the very latest master branch, i.e. commit f5f055dc3a51ac01bf4a554d6f7aaa56878e53b1), this test works and returns `true`.

**Comment by cdwensley** [comment]
Indeed, now working for me, and all the Kan tests pass.  Thank you - for whatever it is that you have done.
